### ISSUE TITLE
Allow reconfiguration to set station id and the API Key

### ISSUE THREAD

**Issue by ncmarket** [briis/weatherflow_forecast#151]
**Is your feature request related to a problem? Please describe.**
Yes, I had strange authentication issues with the integration after it worked for a while, one year. I revalidated the API key but was unable to validate the station id.

**Describe the solution you'd like**
In the reconfiguration dialog, we should show and allow editing of the station id and API key

**Describe alternatives you've considered**
There does not seem to be another easy alternative, I tried to locate the configuration files in the file system. But that is beyond the skillset of some users.
**Additional context**

**Comment by briis** [comment]
You can re-enter the API key after installation, by clicking on the Configure Button on the Integration page, but as the Station ID is the key this cannot be changed afterwards. The reason is that this is the key, when you run multiple installations of WeatherFlow, and it is part of the Unique ID for all sensors.
So in the case you need to change the Station ID, you will have to delete the Integration, as stated you though change the API key after installation.
