### ISSUE TITLE
Weather card

### ISSUE THREAD

**Issue by verstrepeng** [briis/weatherflow_forecast#17]
Hi Bjarne,
I just migrated from the Weatherflow integration to the Weatherflow forecast one, all seems good, I have my sensor data.
Already many thanks for keeping this project up to date !
I was also using your weather-card-extended, which seems deprecated by now ? I changed the entity-id to the new one, but lost my hourly forecast.
Is there any solution, or would you recommend another card ?

KR,
Geert

**Comment by briis** [comment]
As you might know , as of 2023.9 of HA the Weather Entity has changed, so that Forecasts no longer use attributes. Except for the official Weather Card, all the other weather card struggle with the same issue as they depend of the Forecast Attributes. 
I am not a front end developer, so I honestly don't know how to fix the old card you use. So for now use the built-in [Weather Card](https://www.home-assistant.io/dashboards/weather-forecast/)
