### ISSUE TITLE
Failed setup, will retry

### ISSUE THREAD

**Issue by edwardscaleb9** [briis/weatherflow_forecast#70]
**Describe the bug**
All sensors unavailable on previously working integration.
HA logs show "Finished fetching weatherflow_forecast data in xxxx seconds (success: False)"
I've verified my station ID is correct (this integration was working previously).
I've removed the integration from HACS, rebooted, reinstalled the integration, rebooted and I get the same errors.

**To Reproduce**
1. Install Weatherflow Forecast via HACS
2. Add a new station using station ID and API token

**Expected behavior**
Weatherflow sensors and forecast to be added to HA.

**Screenshots**
![image](https://github.com/briis/weatherflow_forecast/assets/10451532/a15dfc68-4665-4457-afe1-a9017175a829)

**Additional context**
HA Core version 2024.1.3
Weatherflow Forecast version 1.0.5

**Comment by bb12489** [comment]
This is happening to me too

**Comment by briis** [comment]
Have you both checked that your stations are still sending data to weatherflow? If you are in the northern hemisphere there is often not enough light to charge the station and it more or less shuts all data down. I am working on a fix that not makes it fail, but just sends the little data that is available.

**Comment by bb12489** [comment]
> Have you both checked that your stations are still sending data to weatherflow? If you are in the northern hemisphere there is often not enough light to charge the station and it more or less shuts all data down. I am working on a fix that not makes it fail, but just sends the little data that is available.

Yup, this is definitely what has happened for mine. I moved it to a much sunnier part of the yard and it's starting to report data now. Appreciate the fix though. It was just concerning to see it fail all of a sudden.

**Comment by briis** [comment]
If one of you still see the error, could you look in the log files, and post that here. As I said I am trying to see if we can avoid it failing, but I need some data to work with. A Station ID could also be useful as I then can retrieve the raw data myself.

**Comment by edwardscaleb9** [comment]
I'm thinking battery charge may also be my issue. Do you just need the log file that's downloaded when debug logging is turned off from the integration setup page? My station ID is 86444.

**Comment by briis** [comment]
I got your Station id, so now I can look at the raw data. Thanks.

**Comment by briis** [comment]
Checked your station, and there is no observation data returned from WeatherFlow. That always indicates that your Hub has not send any data for some time to WeatherFlow. That is almost always caused by one of the following two errors: 
1. Your Hub is Offline - Check that there is a green light at the back of the Hub. If not, remove the power, count to 5 and plug it in again. Once the light is green, it can talk to your Station and to WeatherFlow
2. The Tempest stations battery is too low to transmit data to the hub. The raw data does not show that, but it might be an old value from when it was still sending data.

This gives me some data to work with, but it would really be nice to know if your station is offline or just on very low power.

**Comment by edwardscaleb9** [comment]
Looks like right now it's offline. I'm not at that physical location, so I'll try to troubleshoot next week.

Thank you for looking into this!

**Comment by briis** [comment]
Closed with release 1.0.6. I cannot fix an offline station, but error handling is now ensuring the system does not fail.
